namespace GameLogic
{
    public enum GameState
    {
        Inactive,
        Countdown,
        Play,
        Explosion,
        ReadyToStart,
        Result
    }

    public enum WordCondition
    {
        Begin,
        Anywhere,
        End,
    }

    public static class Constants
    {
        public const float CountdownTime = 5.0f;
        public const float MinBombAliveTime = 10.0f;
        public const float MaxBombAliveTime = 20.0f;
        public const float BonusBombAliveTime = 3;
        public const float AlertBombTime = 5;
        public const float ExplosionCountdownTime = 5;

        public static readonly string[] Cards =
        {
            "кар",
            "co",
            "метр",
            "инк",
            "ем",
            "ан",
            "бри",
            "бы",
            "вни",
            "гон",
            "до",
            "доз",
            "жи",
            "зик",
            "кас",
            "кос",
            "кра",
            "мер",
            "мол",
            // "мор",
            // "пра",
            // "пре",
            // "при",
            // "рен",
            // "ска",
            // "сли",
            // "соль",
            // "тел",
            // "фи",
            // "ча",
            // "чик",
            // "чу",
            // "ши",
            // "ща",
            // "щик",
            // "щу",
            // "чер",
            // "шаб",
            // "кон",
            // "ноп",
            // "нос",
            // "май",
            // "сонь",
            // "лом",
            // "пка",
            // "тер",
            // "ран",
            // "от",
            // "обо",
            // "синь",
            // "мой",
            // "чок",
            // "кет",
            // "доч",
            // "кет",
            // "рад",
            // "лон",
            // "кат",
            // "лец",
            // "лат",
            // "ник",
            // "бен",
            // "вец",
            // "вод",
            // "нал",
            // "ряд",
            // "кет",
            // "ряд",
            // "кет",
            // "рат",
            // "рог",
            // "пог",
            // "пок",
            // "мя",
            // "бан",
            // "узд",
            // "пах",
            // "зем",
            // "пле",
            // "бра",
            // "зна",
            // "корь",
            // "жар",
            // "нец",
            // "нок",
            // "кав",
            // "нок",
            // "чаг",
            // "рик",
            // "хар",
            // "сан",
            // "виш",
            // "сли",
            // "сед",
            // "гор",
            // "шко",
            // "рох",
            // "мен",
            // "сце",
            // "рок",
            // "чаш",
            // "кус",
            // "лин",
            // "лод",
            // "фра",
            // "што",
            // "сня",
            // "лик",
            // "нец"
        };
    }
}